ARG BASE_IMAGE=debian:bookworm
FROM ${BASE_IMAGE} AS base

#include "common.debian"

RUN sed -i 's/# \(en_US.UTF-8\)/\1/' /etc/locale.gen && \
    /usr/sbin/locale-gen

#include "common.gosu"

FROM base AS final

#include "common.label-and-env"

VOLUME [ "/work" ]
WORKDIR /work

#ARG BUILDROOT_VERSION=2025.05
#ENV BUILDROOT_VERSION=${BUILDROOT_VERSION}

#include "common.buildroot"

#ARG USER_PRE_CMD_EXEC="/buildroot.sh"
#ENV USER_PRE_CMD_EXEC=${USER_PRE_CMD_EXEC}

#include "common.entrypoint"

CMD ["/bin/bash", "-l"]

